/**
 * Tech stack icon URLs (tandpfun/skill-icons + simple-icons + devicon for gaps).
 * Keys must match strings in `SkillGroup.items` in portfolio-data.
 */
const SI11 = "https://cdn.jsdelivr.net/npm/simple-icons@11/icons";
const SI14 = "https://cdn.jsdelivr.net/npm/simple-icons@14/icons";
const SK =
  "https://cdn.jsdelivr.net/gh/tandpfun/skill-icons@main/icons" as const;
const DV = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons" as const;

export const SKILL_ICON_SRC: Record<string, string> = {
  JavaScript: `${SK}/JavaScript.svg`,
  TypeScript: `${SK}/TypeScript.svg`,
  "Node.js": `${SK}/NodeJS-Light.svg`,
  Python: `${SK}/Python.svg`,
  SQL: `${SK}/MySQL.svg`,
  HTML: `${SK}/HTML.svg`,
  CSS: `${SK}/CSS.svg`,
  "HTML/CSS": `${SK}/HTML.svg`,
  React: `${SK}/React.svg`,
  "Next.js": `${SK}/NextJS-Light.svg`,
  "Express.js": `${SK}/ExpressJS-Light.svg`,
  NestJS: `${SK}/NestJS-Light.svg`,
  FastAPI: `${SK}/FastAPI.svg`,
  Django: `${SK}/Django.svg`,
  "Tailwind CSS": `${SK}/TailwindCSS-Light.svg`,
  Tailwind: `${SK}/TailwindCSS-Light.svg`,
  "Shadcn UI": `${SK}/React.svg`,
  "Framer Motion": `${SI11}/framermotion.svg`,
  MongoDB: `${SK}/MongoDB.svg`,
  PostgreSQL: `${SK}/PostgreSQL.svg`,
  MySQL: `${SK}/MySQL.svg`,
  Redis: `${SK}/Redis-Light.svg`,
  DynamoDB: `${SK}/DynamoDB-Light.svg`,
  Docker: `${SK}/Docker.svg`,
  Kubernetes: `${SK}/Kubernetes.svg`,
  AWS: `${SK}/AWS-Light.svg`,
  Azure: `${SK}/Azure-Light.svg`,
  "Google Cloud": `${SK}/GCP-Light.svg`,
  GCP: `${SK}/GCP-Light.svg`,
  Jenkins: `${SK}/Jenkins-Light.svg`,
  Terraform: `${SK}/Terraform-Light.svg`,
  Ansible: `${SK}/Ansible.svg`,
  "CI/CD": `${SK}/Git.svg`,
  Linux: `${SK}/Linux-Light.svg`,
  Go: `${SK}/GoLang.svg`,
  Rust: `${SK}/Rust.svg`,
  Java: `${SK}/Java-Light.svg`,
  "REST APIs": `${SK}/Postman.svg`,
  GraphQL: `${SK}/GraphQL-Light.svg`,
  gRPC: `${DV}/grpc/grpc-plain.svg`,
  Prisma: `${SK}/Prisma.svg`,
  "GitHub Actions": `${SK}/GithubActions-Light.svg`,
  Nginx: `${SK}/Nginx.svg`,
  Vue: `${SK}/VueJS-Light.svg`,
  Vite: `${SK}/Vite-Light.svg`,
  Redux: `${SK}/Redux.svg`,
  Figma: `${SK}/Figma-Light.svg`,
  SQLite: `${SK}/SQLite.svg`,
  Supabase: `${SK}/Supabase-Light.svg`,
  Firebase: `${SK}/Firebase-Light.svg`,
  Cassandra: `${SK}/Cassandra-Light.svg`,
  LangChain: `${SI14}/langchain.svg`,
  LangGraph: `${SI14}/langgraph.svg`,
  CrewAI: `${SI14}/crewai.svg`,
  n8n: `${SI14}/n8n.svg`,
  "OpenAI API": `${SI14}/openai.svg`,
  RAG: `${SK}/Python.svg`,
  "Hugging Face": `${SI14}/huggingface.svg`,
  "Prompt Engineering": `${SK}/Python.svg`,
  Cisco: `${SI14}/cisco.svg`,
};
